In [ ]:
!pip install opencv-python

In [ ]:
import cv2
import numpy as np
import os

In [ ]:
import cv2

img = cv2.imread(r"D:\Image Segmentation\tulasi 1\tulasi\2100851874_materiallayer2_eb41417e266baf36a92e63d5299322e3.jpeg")

if img is None:
    print("Error loading image. Check file path.")
else:
    print("Image loaded successfully.")
    img_resized = cv2.resize(img, (800, 600))  # Resize the image
    cv2.imshow("My Window Name", img_resized)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

Image loaded successfully.


In [ ]:
h = np.array([1,2,3,1,2,3])
np.hstack((h,h))
v = np.array([1,2,3,1,2,3])
np.vstack((v,v))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [ ]:
img = cv2.imread(r"D:\Image Segmentation\tulasi 1\tulasi\2100851874_materiallayer2_eb41417e266baf36a92e63d5299322e3.jpeg")
print(img)

[[[ 44  87 150]
  [ 44  87 150]
  [ 43  87 148]
  ...
  [199 201 195]
  [199 201 195]
  [199 201 195]]

 [[ 44  87 150]
  [ 44  87 150]
  [ 43  87 148]
  ...
  [199 201 195]
  [199 201 195]
  [199 201 195]]

 [[ 44  87 150]
  [ 44  87 150]
  [ 43  87 148]
  ...
  [199 201 195]
  [199 201 195]
  [199 201 195]]

 ...

 [[ 16  34  57]
  [ 16  34  57]
  [ 16  34  57]
  ...
  [122 162  97]
  [189 213 171]
  [236 255 222]]

 [[ 16  34  57]
  [ 16  34  57]
  [ 16  34  57]
  ...
  [188 215 171]
  [236 243 230]
  [255 255 255]]

 [[ 16  34  57]
  [ 16  34  57]
  [ 16  34  57]
  ...
  [242 255 230]
  [255 255 255]
  [255 244 255]]]


Collage

In [ ]:
img = cv2.imread(r"D:\Image Segmentation\tulasi 1\tulasi\2100851874_materiallayer2_eb41417e266baf36a92e63d5299322e3.jpeg")
img_re = cv2.resize(img,(300,300))
h = np.hstack((img_re,img_re))
v = np.vstack((h,h))
cv2.imshow("My Window", v)
cv2.waitKey(0)
cv2.destroyAllWindows()

Slideshow

In [ ]:
list_name = os.listdir(r"D:\Image Segmentation\tulasi 1\OpenCV practice")
list_name

['2100866642_materialayer1_ddee069b4f089ff388946b1bd7423a9d.jpeg',
 '2100866642_materiallayer2_16c555dc4a71c9d24cbf071ff79a2c4f.jpeg',
 '2100866642_materiallayer3_f5c02196269dd5b94c3f170695756161.jpeg',
 '2100868469_materiallayer2_709f26ddf8ed4918ad9bfb6ea794d1ec.jpeg',
 '2100868470_materialayer1_7ce2a4ccdfcae713bb50c6ce99f0cd7d.jpeg',
 '2100868475_materiallayer2_b389025f3db76c0d8a5b1bc14e2306b6.jpg']

In [ ]:
for name in list_name:
    path = "D:\\Image Segmentation\\tulasi 1\\OpenCV practice"
    img_name = path + "\\" + name
    img = cv2.imread(img_name)
    img = cv2.resize(img, (400,600))
    cv2.imshow("My Window", img)
    cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
img = cv2.imread(r"D:\Image Segmentation\tulasi 1\tulasi\2100851874_materiallayer2_eb41417e266baf36a92e63d5299322e3.jpeg")
print(img.shape)

(1280, 960, 3)


In [ ]:
!jupyter --version

Selected Jupyter core packages...
IPython          : 8.27.0
ipykernel        : 6.28.0
ipywidgets       : 7.8.1
jupyter_client   : 8.6.0
jupyter_core     : 5.7.2
jupyter_server   : 2.14.1
jupyterlab       : 4.2.5
nbclient         : 0.8.0
nbconvert        : 7.16.4
nbformat         : 5.10.4
notebook         : 7.2.2
qtconsole        : 5.5.1
traitlets        : 5.14.3


Image Read and show in detail

In [ ]:
#in openCV it follows gbr rather than rgbabs
#cv2.imread(path,0/1/-1) 0,1,-1 aka flag values, 1:it gives colour image, 0: greyscale image, -1: alpha value
#shape changes in the greyscale image
img = cv2.imread(r"D:\Image Segmentation\tulasi 1\OpenCV practice\download.jfif",1)
print(img.shape)
img = cv2.resize(img, (300,500))
cv2.imshow("Tulasi", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(183, 275, 3)


Text over an image

In [ ]:
img_get = cv2.imread(r"D:\Image Segmentation\tulasi 1\OpenCV practice\download.jfif")
img_get = cv2.resize(img_get, (400,300))

txt1 = cv2.putText(img = img_get,
    text = "Fruit Basket",
    org = (50,50),
    fontFace = cv2.FONT_HERSHEY_DUPLEX,
    fontScale = 1, #font size
    color = (0,0,0),
    thickness = 3,
    lineType = cv2.LINE_8,
    bottomLeftOrigin = False
)
#parameters: img, text, org, fontFace, fontScale, color[, thickness[, lineType[, bottomLeftOrigin]]]
#Bottom left origin: mirror image
cv2.imshow("Tulasi", txt1)
cv2.waitKey(0)
cv2.destroyAllWindows()

Line and Rectangle on Images

In [ ]:
img = cv2.imread(r"D:\Image Segmentation\tulasi 1\OpenCV practice\download.jfif")
img = cv2. resize(img, (500,400))

img_line = cv2.line(img=img, pt1 = (100,123), pt2= (400,110), color= (0,225,0), thickness= 3, lineType= 6)
cv2.imshow("Tulasi", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
img = cv2.imread(r"D:\Image Segmentation\tulasi 1\OpenCV practice\download.jfif")
img = cv2. resize(img, (500,400))

txt1 = cv2.putText(img = img,
    text = "Fruit Basket",
    org = (50,50),
    fontFace = cv2.FONT_HERSHEY_DUPLEX,
    fontScale = 1, #font size
    color = (234,124,245),
    thickness = 2,
    lineType = cv2.LINE_8,
    bottomLeftOrigin = False
)
img_rect = cv2.rectangle(img=img, pt1 = (100,70), pt2= (400,350), color= (255,0,0), thickness= 3, lineType= 6)
cv2.imshow("Tulasi", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Circle and Ecllipse

In [ ]:
img = cv2.imread(r"D:\Image Segmentation\tulasi 1\OpenCV practice\download.jfif")
img = cv2. resize(img, (500,400))
img_circle = cv2.circle(
img= img,
center = (240,200) ,
radius = 150,
color = (0,255,0),
thickness=3,
lineType = 16
)
cv2.imshow("Tulasi", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
img = cv2.imread(r"D:\Image Segmentation\tulasi 1\OpenCV practice\download.jfif")
img = cv2. resize(img, (500,400))
img_circle = cv2.ellipse(
img = img,
center=(240,200),
axes = (50,100),
angle = 170 ,
startAngle=0,
endAngle=360,
color=(0,255,2),
thickness=2,
lineType = 4
)
cv2.imshow("Tulasi", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Arthematic Operations with Images

In [ ]:
#ADD IMAGE

img1 = cv2.imread(r"D:\Image Segmentation\tulasi 1\Approved - mixscrap\2100848504_materialayer1_5b42d6bcf44d1bc13eec5ea37bce6dc4.jpeg")
img2 = cv2.imread(r"D:\Image Segmentation\tulasi 1\OpenCV practice\download.jfif")

#resize to same pixels
img1 = cv2.resize(img1, (500,600))
img2 = cv2.resize(img2, (500,600))

#aplha: intensity of image ranged 0-1; beta: intensity of image2 , gamma: intensity of merged image
#more you wanna see image keep intensity high

new_img_add = cv2.addWeighted(img1,0.1,img2,1,.9)

cv2.imshow("tulasi", new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# SUBTRACT IMAGE

img1 = cv2.imread(r"D:\Image Segmentation\tulasi 1\Approved - mixscrap\2100848504_materialayer1_5b42d6bcf44d1bc13eec5ea37bce6dc4.jpeg")
img2 = cv2.imread(r"D:\Image Segmentation\tulasi 1\OpenCV practice\download.jfif")

#resize to same pixels
img1 = cv2.resize(img1, (500,600))
img2 = cv2.resize(img2, (500,600))

#aplha: intensity of image ranged 0-1; beta: intensity of image2 , gamma: intensity of merged image
#more you wanna see image keep intensity high

new_img_sub = cv2.subtract(img1,img2)

cv2.imshow("tulasi", new_img_sub)
cv2.waitKey(0)
cv2.destroyAllWindows()

Bitwise Operations on Binary Images

In [ ]:
import numpy as np

In [ ]:
#Binary Images: Image with only 2 channels black(0) and white(1)
#Bitwise Operators: AND, OR, NOT, XOR
# AND: If both of channels are 1 then it gives 1, if both are 0 then 0, but if both are different like 0,1 or 1,0 it gives us 0.
# OR: If either one of it is 1 it gives 1 and if both are 0 gives 0, both are 1 then 1
#XOR: If both are same then it gives 0 and if both are different it gives 1.
# NOT: if its 0 it converts to 1 and vice versa
img1 = cv2.imread(r"D:\Image Segmentation\tulasi 1\OpenCV practice\yin yang.jfif")
img2 = cv2.imread(r"D:\Image Segmentation\tulasi 1\OpenCV practice\Screenshot 2025-01-10 181034.png")

img1 = cv2.resize(img1,(300,300))
img2 = cv2.resize(img2,(300,300))

# new = cv2.bitwise_and(img1,img2)
# new = cv2.bitwise_or(img1,img2)
# new = cv2.bitwise_xor(img1,img2)
new = cv2.bitwise_not(img1)
new1 = cv2.bitwise_not(img2)

h = np.hstack((img1,new))
h1 = np.hstack((img2,new1))

v = np.vstack((h,h1))

cv2.imshow("tulasi",v)
cv2.waitKey(0)
cv2.destroyAllWindows()



##### Edge Detection

In [ ]:
#For edged images we convert image into greyscale. i.e, from 3 channel image to 2 channel imag

img = cv2.imread(r"D:\Image Segmentation\tulasi 1\OpenCV practice\download.jfif")
img = cv2.resize(img,(400,400))
print(img.shape)
#threshold: how much detialing the new img needs to have, aperturesize: used for changing channels from 3 to 2
#more the threshhold less the detailing
edge_img = cv2.Canny(img,200,200,apertureSize = 5, L2gradient = True)
print(edge_img.shape)

cv2.imshow("tulasi1",edge_img)
cv2.imshow("tulasi",img)

cv2.waitKey(0)
cv2.destroyAllWindows()

(400, 400, 3)
(400, 400)


### Image Scaling & Rotation

In [ ]:
org_img = cv2.imread(r"D:\Image Segmentation\tulasi 1\OpenCV practice\download.jfif")
resize_imag = cv2.resize(org_img,(459,459))

cv2.imshow("tulasi",resize_imag)
cv2.imshow("tulasi1",org_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
org_img = cv2.imread(r"D:\Image Segmentation\tulasi 1\OpenCV practice\download.jfif")
resize_img = cv2.resize(org_img,(459,459))
#w,h are for getting center fo the image
w,h = resize_img.shape[0], resize_img.shape[1]

#matrix (m) is used for rotation purpose to tell by how much the image should rotate.
m = cv2.getRotationMatrix2D((w/2,h/2),75,0.65)
new_img = cv2.warpAffine(resize_img,m,(w,h))

h = np.hstack((resize_img,new_img))
cv2.imshow("tulasi",h)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Image Blurring

In [ ]:
## Guassian Blurring: Soft blur; Median blur: Most used and have sharpened image
img = cv2.imread(r"D:\Image Segmentation\tulasi 1\OpenCV practice\download.jfif")
img = cv2.resize(img,(300,500))

g_blur = cv2.GaussianBlur(img,(5,15),0) #more the kernel size blurrer it gets and the kernels should be odd and positive
m_blur = cv2.medianBlur(img,5)
b_blur = cv2.bilateralFilter(img,15,75,75) #more the d smoother the image

h = np.hstack ((img,g_blur,m_blur,b_blur))
cv2.imshow("tulasi",h)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Saving Images using imwrite

In [ ]:
## Guassian Blurring: Soft blur; Median blur: Most used and have sharpened image
img = cv2.imread(r"D:\Image Segmentation\tulasi 1\OpenCV practice\images.jfif")
img = cv2.resize(img,(132,170))

g_blur = cv2.GaussianBlur(img,(5,15),0) #more the kernel size blurrer it gets and the kernels should be odd and positive
m_blur = cv2.medianBlur(img,5)
b_blur = cv2.bilateralFilter(img,15,75,75) #more the d smoother the image

h = np.hstack ((img,g_blur,m_blur,b_blur))
pp_img = np.vstack((h,h))
cv2.imwrite(r"D:\Image Segmentation\tulasi 1\OpenCV practice\passport_trial.jpeg",pp_img)
cv2.imshow("tulasi",pp_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Borders

In [ ]:
img = cv2.imread(r"D:\Image Segmentation\tulasi 1\OpenCV practice\images.jfif")
img = cv2.resize(img,(132,170))

#Border Styles
img1 = cv2.copyMakeBorder(img,5,5,5,5,cv2.BORDER_CONSTANT,None, value = (255,255,255)) #value is colour
img2 = cv2.copyMakeBorder(img,9,9,9,9,cv2.BORDER_DEFAULT,None, value = 2)

cv2.imshow("tulasi",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Video Playing

In [ ]:
cap = cv2.VideoCapture(r"D:\Image Segmentation\tulasi 1\OpenCV practice\10 SECONDS VIDEO CLIP.mp4")
while cap.isOpened():
    r,frame = cap.read()
    if r == True:
        #frame = cv2.resize(frame,(600,500))) : If we wanna resize the video
        cv2.imshow("tulasi",frame)
        if cv2.waitKey(20) & 0xff == ord("p"): #the more the number inside the waitKey slower the video runs
            break            #press p if you wanna exit
    else:
        break

cap.release()
cv2.destroyAllWindows()

### Camera Access

In [ ]:
cap = cv2.VideoCapture(0)
while True:
    r,frame = cap.read()
    if r == True:
        #frame = cv2.resize(frame,(600,500))) : If we wanna resize the video
        cv2.imshow("tulasi",frame)
        if cv2.waitKey(20) & 0xff == ord("p"): #the more the number inside the waitKey slower the video runs
            break            #press p if you wanna exit
    else:
        break

cap.release()
cv2.destroyAllWindows()

### Morphological Operations

 Used to extract image components that are useful in the representation and description of region shape.
 Perfoemd on binary images (Black and white)

 **Types of morphological Operations**
- Erosion: Erodes away the boundaries of fg obj. Mostly fg are white. Used to remove white noises.
- Dilation: Opposite of erosion.Changes black to white channels.
- Opening: Removes the noise. Erosion followed by dilation
- Closing: Dilation followed by erosion.
- Gradient morphological: Dilation - Erosion. It creates like a boundary
- Top hat/White hat: Input image - output image. The most rewritten parts of white is changed to black.
- Black hat: The most rewritten parts of white are kept.

In [ ]:
img = cv2.imread(r"D:\Image Segmentation\tulasi 1\OpenCV practice\BW image.png")
img = cv2.resize(img,(200,200))

m = np.ones((5,5),np.uint8) #bigger the matrix thinner the image becomes
m1 = np.ones((10,10),np.uint8)
#Erosion
er = cv2.erode(img,m,iterations = 1)
er1 = cv2.erode(img,m1,iterations = 1)
#Dilate
di = cv2.dilate(img,m,iterations = 1)
#Opening
op = cv2.morphologyEx(img,cv2.MORPH_OPEN,m,iterations = 1)
#Closing
cl = cv2.morphologyEx(img,cv2.MORPH_CLOSE,m, iterations =1)
# Morphological Grdient
gr = cv2.morphologyEx(img,cv2.MORPH_GRADIENT,m, iterations =1)
#Top hat
th = cv2.morphologyEx(img,cv2.MORPH_TOPHAT,m, iterations =1)
#Black Hat
bh = cv2.morphologyEx(img,cv2.MORPH_BLACKHAT,m, iterations =1)

h = np.hstack((img,cl,op,gr,th,bh))
cv2.imshow("tulasi",h)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Image Pyramid